#!/usr/bin/env bash

function pushdq() { pushd ${1} &>/dev/null; }
function popdq() { popd &>/dev/null; }

function main() {
	local rootRelDir="$(dirname "${0}")"
	local binRelDir="${rootRelDir}/.bin"

	mkdir -p "${binRelDir}"
	echo ${PWD}
	rm "${binRelDir}/"*
	pushdq "${binRelDir}"
	export GOBIN="${PWD}"
	popdq

	pushdq "${rootRelDir}"
	go generate -tags tools "${rootRelDir}"
	popdq

	unset GOBIN
}

main
